module.exports = {
  projects: [
    'packages/auth',
    'packages/core',
    'packages/drizzle',
    'packages/express',
    'packages/fastify',
    'packages/gen',
    'packages/graphql',
    'packages/hono',
    'packages/mikro-orm',
    'packages/mongoose',
    'packages/nest',
    'packages/prisma',
    'packages/react',
    'packages/solid',
    'packages/svelte',
    'packages/trpc',
    'packages/typeorm',
    'packages/validation',
    'apps/demo-full',
  ],
};
