export const ENTITY_NAME_TOKEN = 'entity-name'//TODO deprecate this
export const FIELDS_TOKEN = 'fields'//TODO deprecate this
export const GEN_CRUD_METHOD_TOKEN = 'gen-crud-method'//TODO deprecate this
export const GEN_DATA_DICT_TOKEN = 'gen-data-dict'//TODO deprecate this
export const IGNORE_FIEIDS_TOKEN = 'ignore-fields' //TODO deprecate this
export const CRUD_OPTION = 'crud-option'
export type HttpMethods = 'get' | 'post' | 'put' | 'delete' | 'patch'
export type CRUDMethods = 'create' | 'read' | 'update' | 'delete'
export const BEFORE_ACTION_TOKEN = 'before-action'
export type BeforeActionTokenType = `before-action-${CRUDMethods}`
export const defaultCrudMethod = ['create', 'read', 'update', 'delete']
export const FCRUD_GEN_CFG_TOKEN = 'fast-crud-config-gen'